"""Berkeley real estate regulations knowledge base.

Loads structured regulation data from JSON files in ``data/regulations/``.
Used by the Faketor AI chat service via the ``lookup_regulation`` tool.

The JSON files are generated by the regulation data pipeline
(``homebuyer collect regulations``).  Run that command to populate or
update the data from official Berkeley sources.

Sources:
    - Berkeley Municipal Code Title 23 (Zoning Ordinance)
      https://berkeley.municipal.codes/BMC/23
    - City of Berkeley Planning & Development
      https://berkeleyca.gov/construction-development/
    - California Government Code (ADU, SB 9, Middle Housing)
"""

from __future__ import annotations

import logging
import re
from typing import Optional

from homebuyer.config import REGULATIONS_DIR
from homebuyer.utils.file_utils import load_json_data as _load_json

logger = logging.getLogger(__name__)


# Load zone definitions and regulation categories at import time.
# If JSON files are missing, fall back to empty dicts with a warning.
ZONE_DEFINITIONS: dict[str, dict] = {}
REGULATIONS: dict[str, dict] = {}

_zones_path = REGULATIONS_DIR / "zones.json"
_categories_path = REGULATIONS_DIR / "categories.json"

if _zones_path.exists():
    ZONE_DEFINITIONS = _load_json(_zones_path)
    logger.debug("Loaded %d zone definitions from %s", len(ZONE_DEFINITIONS), _zones_path)
else:
    logger.warning(
        "Zone definitions not found at %s — run 'homebuyer collect regulations'",
        _zones_path,
    )

if _categories_path.exists():
    REGULATIONS = _load_json(_categories_path)
    logger.debug(
        "Loaded %d regulation categories from %s", len(REGULATIONS), _categories_path
    )
else:
    logger.warning(
        "Regulation categories not found at %s — run 'homebuyer collect regulations'",
        _categories_path,
    )


# ---------------------------------------------------------------------------
# Lookup helpers
# ---------------------------------------------------------------------------

# Pre-compiled pattern for extracting zone codes from free text
_ZONE_CODE_RE = re.compile(
    r"\b(R-[1-5][AH]*|ES-R|MU-?R|MULI|C-[A-Z]{1,3}(?:\s*\(H\))?|M)\b",
    re.IGNORECASE,
)

# Build keyword → category mapping dynamically from the ``keywords``
# arrays in each category entry.  Falls back to a hardcoded default
# if the JSON data does not include keywords (e.g. legacy seed).
_KEYWORD_MAP: dict[str, str] = {}
for _cat_key, _cat_data in REGULATIONS.items():
    for _kw in _cat_data.get("keywords", []):
        _KEYWORD_MAP[_kw] = _cat_key

# If JSON didn't provide keywords, use hardcoded fallback
if not _KEYWORD_MAP:
    _KEYWORD_MAP = {
        "adu": "adu_rules",
        "accessory dwelling": "adu_rules",
        "jadu": "adu_rules",
        "junior adu": "adu_rules",
        "granny flat": "adu_rules",
        "in-law": "adu_rules",
        "sb9": "sb9_lot_splitting",
        "sb 9": "sb9_lot_splitting",
        "lot split": "sb9_lot_splitting",
        "lot splitting": "sb9_lot_splitting",
        "middle housing": "middle_housing",
        "duplex": "middle_housing",
        "triplex": "middle_housing",
        "fourplex": "middle_housing",
        "cottage court": "middle_housing",
        "beso": "beso",
        "energy audit": "beso",
        "energy assessment": "beso",
        "emissions": "beso",
        "transfer tax": "transfer_tax",
        "city tax": "transfer_tax",
        "real estate tax": "transfer_tax",
        "rent control": "rent_control",
        "rent stabilization": "rent_control",
        "tenant": "rent_control",
        "eviction": "rent_control",
        "vacancy decontrol": "rent_control",
        "permit": "permitting",
        "permitting": "permitting",
        "building permit": "permitting",
        "plan check": "permitting",
        "hillside": "hillside_overlay",
        "h suffix": "hillside_overlay",
        "hill overlay": "hillside_overlay",
        "fire hazard": "hillside_overlay",
        "zoning": "zoning_codes",
        "zone code": "zoning_codes",
        "zoning code": "zoning_codes",
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def lookup_regulation(
    topic: str,
    zone_code: Optional[str] = None,
) -> dict:
    """Look up Berkeley regulation by topic and optional zone code.

    Args:
        topic: Regulation topic — a category key (e.g., ``"adu_rules"``) or
            natural language (e.g., ``"what is R-1H"``).
        zone_code: Optional zone code for zone-specific lookups.

    Returns:
        Dict with matched regulation content including ``title``,
        ``summary``, ``details``, ``source``, and optionally ``zone``.
    """
    topic_lower = topic.strip().lower()

    # 1. Exact category key match
    if topic_lower in REGULATIONS:
        result = dict(REGULATIONS[topic_lower])
        result["category"] = topic_lower
        # If zone_code provided with zoning_codes, add specific zone info
        if zone_code and topic_lower == "zoning_codes":
            zone_upper = zone_code.strip().upper()
            if zone_upper in ZONE_DEFINITIONS:
                result["zone"] = {zone_upper: ZONE_DEFINITIONS[zone_upper]}
        return result

    # 2. Zone code extraction — from explicit parameter or from topic text
    target_zone = None
    if zone_code:
        target_zone = zone_code.strip().upper()
    else:
        match = _ZONE_CODE_RE.search(topic)
        if match:
            target_zone = match.group(1).upper()

    if target_zone and target_zone in ZONE_DEFINITIONS:
        zone_info = ZONE_DEFINITIONS[target_zone]
        return {
            "category": "zoning_codes",
            "title": f"Zone {target_zone}: {zone_info['name']}",
            "summary": zone_info["description"],
            "details": zone_info["description"],
            "zone": {target_zone: zone_info},
            "hillside_overlay": zone_info.get("hillside", False),
            "source": "Berkeley Municipal Code Title 23",
            "related": (
                ["hillside_overlay"] if zone_info.get("hillside") else []
            ),
        }

    # 3. Keyword matching
    for keyword, category_key in _KEYWORD_MAP.items():
        if keyword in topic_lower:
            result = dict(REGULATIONS[category_key])
            result["category"] = category_key
            return result

    # 4. Not found — return available categories
    return {
        "category": None,
        "title": "Topic Not Found",
        "summary": f"No regulation found matching '{topic}'.",
        "available_categories": list(REGULATIONS.keys()),
        "available_zones": sorted(ZONE_DEFINITIONS.keys()),
        "hint": (
            "Try a category key like 'adu_rules', 'transfer_tax', "
            "'hillside_overlay', or a zone code like 'R-1H', 'C-SA'."
        ),
    }
