import { ArrowLeft } from 'lucide-react';

const TOS_VERSION = '1.0';
const EFFECTIVE_DATE = 'March 12, 2026';

export function TermsPage({ onBack }: { onBack?: () => void }) {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="mx-auto max-w-3xl">
        {onBack && (
          <button
            onClick={onBack}
            className="mb-6 flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700 transition-colors"
          >
            <ArrowLeft size={16} />
            Back
          </button>
        )}

        <div className="rounded-xl border border-gray-200 bg-white p-8 md:p-12 shadow-sm">
          <h1 className="text-2xl font-bold text-gray-900 mb-1">Terms and Conditions</h1>
          <p className="text-sm text-gray-500 mb-8">
            Version {TOS_VERSION} &middot; Effective {EFFECTIVE_DATE}
          </p>

          <div className="prose prose-sm prose-gray max-w-none space-y-6 text-gray-700 leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">1. What This Is</h2>
              <p>
                HomeBuyer is a personal side project that provides AI-powered real estate analytics
                for Berkeley, CA. It is not a commercial product, not a licensed real estate
                brokerage, and not a financial advisory service. It is built and maintained by one
                person in their spare time. By creating an account, you agree to these terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">2. AI-Generated Content Disclaimer</h2>
              <p>
                HomeBuyer uses artificial intelligence (Claude by Anthropic) to generate property
                valuations, market analysis, zoning interpretations, and other real estate insights.
                <strong> This content is generated by AI and may be inaccurate, incomplete, or
                outdated.</strong>
              </p>
              <p>
                AI outputs do not constitute real estate advice, financial advice, legal advice,
                investment advice, or any form of professional counsel. You should not make
                purchasing, selling, or investment decisions based solely on information from this
                application. Always consult qualified professionals (licensed real estate agents,
                attorneys, financial advisors) before making real estate decisions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">3. No Warranty / As-Is</h2>
              <p>
                This service is provided "as is" and "as available" without warranties of any kind,
                either express or implied. We make no guarantees regarding accuracy, reliability,
                availability, or fitness for any particular purpose. The service may contain errors,
                be temporarily unavailable, or be discontinued at any time without notice.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Data and Privacy</h2>
              <p>
                When you create an account, we store your email address, an optional display name,
                and a hashed version of your password. We also store your conversation history and
                search queries to provide the service. We do not sell, share, or monetize your
                personal data. We do not use your data for advertising purposes.
              </p>
              <p>
                Property data displayed in the application is sourced from public records and
                publicly available information.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">5. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, the creator of HomeBuyer shall not be liable
                for any direct, indirect, incidental, consequential, or special damages arising from
                your use of this service, including but not limited to financial losses from real
                estate decisions influenced by this application's output.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">6. User Conduct</h2>
              <p>
                You agree not to misuse the service, including but not limited to: automated
                scraping or data extraction, attempting to reverse-engineer the AI models, using
                the service to harass or harm others, or creating multiple accounts to circumvent
                usage limits.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Account Termination</h2>
              <p>
                We reserve the right to suspend or terminate accounts at our sole discretion,
                with or without notice. We may also discontinue the entire service at any time.
                You may delete your account at any time by contacting us.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Changes to These Terms</h2>
              <p>
                We may update these terms from time to time. When we do, we will update the version
                number and effective date at the top of this page. Continued use of the service
                after changes constitutes acceptance of the updated terms. For significant changes,
                we may prompt you to re-accept.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Contact</h2>
              <p>
                If you have questions about these terms, you can reach the project maintainer
                via the GitHub repository where this project is hosted.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}

export { TOS_VERSION };
